schema_version: 1

context:
  version: "1.20.2+go1.20.14"

package:
  name: gopherjs
  version: ${{ version }}

source:
  url: https://github.com/gopherjs/gopherjs/archive/v${{ version }}.tar.gz
  sha256: 83d8e28e2eda1b8e396da3b9d5a6c41752016b472219310357584f2f56328d71

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - gopherjs --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A compiler from Go to JavaScript for running Go code in a browser
  homepage: https://github.com/gopherjs/gopherjs
  repository: https://github.com/gopherjs/gopherjs

extra:
  recipe-maintainers:
    - danielnachun
