schema_version: 1

context:
  version: "1.20.1"

package:
  name: gopherjs
  version: ${{ version }}

source:
  url: https://github.com/gopherjs/gopherjs/archive/v${{ version }}.tar.gz
  sha256: 9f1fe87e4b7ecc29a58ad541c822cacaf28ebc43ff0ffe73ecd0a867f5b0cc68

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - gopherjs --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A compiler from Go to JavaScript for running Go code in a browser
  homepage: https://github.com/gopherjs/gopherjs
  repository: https://github.com/gopherjs/gopherjs

extra:
  recipe-maintainers:
    - danielnachun
